#!/usr/bin/env python
"""Generate ``Frontend/src/lib/resolutionLabels.ts`` from the shared
``Backend/app/schemas/resolution_labels.json`` so the backend and frontend
resolution-path label maps can never silently drift.

Workflow:
    1. Edit ``Backend/app/schemas/resolution_labels.json`` (the single source).
    2. Run:  ``python Backend/scripts/gen_resolution_labels.py``
    3. Commit the regenerated ``resolutionLabels.ts``.

The backend loads the JSON directly at runtime (no generation needed there).
``tests/test_resolution_labels_codegen.py`` fails if the committed TS is stale.
"""
from __future__ import annotations

import json
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]  # .../Backend
REPO_ROOT = BACKEND_DIR.parent
JSON_PATH = BACKEND_DIR / "app" / "schemas" / "resolution_labels.json"
TS_PATH = REPO_ROOT / "Frontend" / "src" / "lib" / "resolutionLabels.ts"

_TEMPLATE = r"""// @generated by Backend/scripts/gen_resolution_labels.py from
// Backend/app/schemas/resolution_labels.json — DO NOT EDIT BY HAND.
// Edit the JSON, then run `python Backend/scripts/gen_resolution_labels.py`.
//
// Single source of truth for resolution-path → human label, shared with the
// backend (Backend/app/schemas/resolution.py loads the same JSON at runtime).
import type { ResolutionPathEnum } from '@/lib/api';

export const RESOLUTION_PATH_LABELS: Record<ResolutionPathEnum, string> = {
__ENTRIES__
};

/**
 * Friendly label for a resolution path. An unknown/new code is humanized
 * ("SOME_NEW_PATH" → "Some New Path") rather than rendered blank — matching the
 * backend `resolution_path_label` fallback. Empty/null returns "—".
 */
export function resolutionPathLabel(code: string | null | undefined): string {
  if (!code) return '—';
  return (
    RESOLUTION_PATH_LABELS[code as ResolutionPathEnum] ??
    code.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
  );
}
"""


def _ts_string(value: str) -> str:
    """Render a JS single-quoted string literal, escaping backslash + quote."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def load_labels() -> dict[str, str]:
    return json.loads(JSON_PATH.read_text(encoding="utf-8"))


def render_ts(labels: dict[str, str]) -> str:
    """Render the full TS module text for ``labels`` (deterministic)."""
    entries = "\n".join(f"  {key}: {_ts_string(val)}," for key, val in labels.items())
    return _TEMPLATE.replace("__ENTRIES__", entries)


def main() -> int:
    TS_PATH.write_text(render_ts(load_labels()), encoding="utf-8", newline="\n")
    print(f"wrote {TS_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
