"""add vendor profile column

Revision ID: 42a0cabaea47
Revises: dcdad0eb0548
Create Date: 2026-06-15 00:04:03.749834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a0cabaea47'
down_revision: Union[str, Sequence[str], None] = 'dcdad0eb0548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add vendors.profile (full VendorProfile snapshot).

    server_default '{}' backfills any existing rows so the NOT NULL add is safe;
    the ORM supplies the value on new inserts.
    """
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("profile", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
