"""initial normalized schema

Revision ID: dcdad0eb0548
Revises: 
Create Date: 2026-06-14 23:52:43.692072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdad0eb0548'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_batches',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('source_file_hash', sa.String(length=128), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('processed_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by', sa.String(length=256), nullable=True),
    sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_batches_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('vendors',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('vendor_name', sa.String(length=256), nullable=False),
    sa.Column('total_invoices_seen', sa.Integer(), nullable=False),
    sa.Column('total_amount_processed', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('exception_type_counts', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('tenant_id', 'vendor_name', name='uq_vendor_tenant_name')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_vendor_name'), ['vendor_name'], unique=False)

    op.create_table('exceptions',
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('invoice_id', sa.String(length=64), nullable=False),
    sa.Column('vendor_name', sa.String(length=256), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=True),
    sa.Column('exception_type', sa.String(length=64), nullable=False),
    sa.Column('exception_description', sa.Text(), nullable=False),
    sa.Column('days_outstanding', sa.Integer(), nullable=False),
    sa.Column('approver_assigned', sa.String(length=256), nullable=True),
    sa.Column('source_file_name', sa.String(length=512), nullable=True),
    sa.Column('uploaded_by', sa.String(length=256), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('exception_id'),
    sa.UniqueConstraint('batch_id', 'invoice_id', name='uq_exc_batch_invoice')
    )
    with op.batch_alter_table('exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exceptions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exceptions_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exceptions_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exceptions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exceptions_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('agent_executions',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('exception_id', sa.Uuid(), nullable=True),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('node_input', sa.JSON(), nullable=True),
    sa.Column('node_output', sa.JSON(), nullable=True),
    sa.Column('success_flag', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_executions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_exception_id'), ['exception_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_execution_timestamp'), ['execution_timestamp'], unique=False)

    op.create_table('classifications',
    sa.Column('classification_id', sa.Uuid(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('primary_exception_type', sa.String(length=64), nullable=False),
    sa.Column('root_cause_hypothesis', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('severity_ai_suggested', sa.String(length=16), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('classified_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classification_id')
    )
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classifications_exception_id'), ['exception_id'], unique=False)

    op.create_table('communications',
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('email_type', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient_email', sa.String(length=320), nullable=True),
    sa.Column('cc_email', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.Column('template_id', sa.String(length=128), nullable=True),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('sent_flag', sa.Boolean(), nullable=False),
    sa.Column('sent_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('message_id', sa.String(length=256), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email_id')
    )
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communications_delivery_status'), ['delivery_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_exception_id'), ['exception_id'], unique=False)

    op.create_table('priorities',
    sa.Column('priority_id', sa.Uuid(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('priority_bucket', sa.String(length=16), nullable=False),
    sa.Column('ranking_position', sa.Integer(), nullable=True),
    sa.Column('drivers', sa.JSON(), nullable=False),
    sa.Column('last_priority_update', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('priority_id')
    )
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priorities_exception_id'), ['exception_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_priorities_priority_bucket'), ['priority_bucket'], unique=False)

    op.create_table('resolutions',
    sa.Column('resolution_id', sa.Uuid(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('resolution_path', sa.String(length=48), nullable=False),
    sa.Column('assigned_team', sa.String(length=128), nullable=True),
    sa.Column('assigned_user', sa.String(length=256), nullable=True),
    sa.Column('resolution_status', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=True),
    sa.Column('rule_version', sa.String(length=64), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('requires_communication', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resolution_id')
    )
    with op.batch_alter_table('resolutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolutions_exception_id'), ['exception_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resolutions_resolution_status'), ['resolution_status'], unique=False)

    op.create_table('status_history',
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.String(length=256), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('changed_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_exception_id'), ['exception_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_exception_id'))

    op.drop_table('status_history')
    with op.batch_alter_table('resolutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolutions_resolution_status'))
        batch_op.drop_index(batch_op.f('ix_resolutions_exception_id'))

    op.drop_table('resolutions')
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priorities_priority_bucket'))
        batch_op.drop_index(batch_op.f('ix_priorities_exception_id'))

    op.drop_table('priorities')
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communications_exception_id'))
        batch_op.drop_index(batch_op.f('ix_communications_delivery_status'))

    op.drop_table('communications')
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classifications_exception_id'))

    op.drop_table('classifications')
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_executions_execution_timestamp'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_exception_id'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_batch_id'))

    op.drop_table('agent_executions')
    with op.batch_alter_table('exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exceptions_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_exceptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_exceptions_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_exceptions_current_status'))
        batch_op.drop_index(batch_op.f('ix_exceptions_batch_id'))

    op.drop_table('exceptions')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_vendor_name'))
        batch_op.drop_index(batch_op.f('ix_vendors_tenant_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_batches_tenant_id'))

    op.drop_table('upload_batches')
    # ### end Alembic commands ###
