// @generated by Backend/scripts/gen_resolution_labels.py from
// Backend/app/schemas/resolution_labels.json — DO NOT EDIT BY HAND.
// Edit the JSON, then run `python Backend/scripts/gen_resolution_labels.py`.
//
// Single source of truth for resolution-path → human label, shared with the
// backend (Backend/app/schemas/resolution.py loads the same JSON at runtime).
import type { ResolutionPathEnum } from '@/lib/api';

export const RESOLUTION_PATH_LABELS: Record<ResolutionPathEnum, string> = {
  AUTO_APPROVE: 'Auto Approve',
  REQUEST_PO: 'Request PO',
  REQUEST_GRN: 'Request GRN',
  ESCALATE_CONTROLLER: 'Escalate to Controller',
  HOLD_INVESTIGATION: 'Hold for Investigation',
  VENDOR_VALIDATION_REVIEW: 'Vendor Validation Review',
  MANUAL_REVIEW: 'Manual Review',
};

/**
 * Friendly label for a resolution path. An unknown/new code is humanized
 * ("SOME_NEW_PATH" → "Some New Path") rather than rendered blank — matching the
 * backend `resolution_path_label` fallback. Empty/null returns "—".
 */
export function resolutionPathLabel(code: string | null | undefined): string {
  if (!code) return '—';
  return (
    RESOLUTION_PATH_LABELS[code as ResolutionPathEnum] ??
    code.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
  );
}
